# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatroom.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 631)
        palette = QtGui.QPalette()
        palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(QtGui.QPixmap("gui/background.png")))
        Form.setPalette(palette)
        Form.setStyleSheet("*{\n"
"font-size:24px;\n"
"font-family:Century Gothic;\n"
"}\n"
"QFrame{\n"
"background:rgba(0,0,0,0.8);\n"
"border-radius:15px;\n"
"}\n"
"#Widget{\n"
"background:url(D:/pictures/sunrise.jpg);\n"
"}\n"
"\n"
"QToolButton{\n"
"background:red;\n"
"border-radius:60px;\n"
"}\n"
"\n"
"#Form\n"
"{\n"
"background : url(gui/background.jpg);\n"
"}\n"
"\n"
"QLabel{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"QPushButton{\n"
"background:red;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover{\n"
"background:#333;\n"
"border-radius:15px;\n"
"background:#49ebff;\n"
"}\n"
"QLineEdit{\n"
"background:transparent;\n"
"border:none;\n"
"color:white;\n"
"border-bottom:1px solid #717072;\n"
"}")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(70, 110, 561, 501))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 20, 311, 51))
        self.label.setStyleSheet("QLabel{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"\n"
"*{\n"
"font-size:24px;\n"
"font-family:Century Gothic;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.send_button = QtWidgets.QPushButton(self.frame)
        self.send_button.setGeometry(QtCore.QRect(460, 450, 91, 41))
        self.send_button.setStyleSheet("")
        self.send_button.setObjectName("pushButton")
        self.content = QtWidgets.QTextBrowser(self.frame)
        self.content.setGeometry(QtCore.QRect(0, 70, 561, 311))
        self.content.setObjectName("content")
        self.content.setStyleSheet("color: white;")  # Set the text color to white
        self.message = QtWidgets.QLineEdit(self.frame)
        self.message.setGeometry(QtCore.QRect(10, 390, 531, 51))
        self.message.setObjectName("message")
        self.toolButton = QtWidgets.QToolButton(Form)
        self.toolButton.setGeometry(QtCore.QRect(290, 10, 121, 121))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(64, 64))
        self.toolButton.setObjectName("toolButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "CHAT HERE"))
        self.send_button.setText(_translate("Form", "send"))
        self.message.setPlaceholderText(_translate("Form", "Please enter the content of the send"))
